- .github/workflows/lint.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- scripts/protocgen.sh
Removes the private module dependencies and CI configs
---
> chore: remove private module dependencies

- .github/workflows/lint.yml
- .github/workflows/release-sims.yml
- .github/workflows/sims.yml
- .github/workflows/stale.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
Uses the github app token rather than the bot account token for actions permission.
---
> chore: replace to github app token for actions

- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
> docs: update swagger for wasm

- .github/workflows/sims.yml
- .github/workflows/test.yml
- baseapp/baseapp.go
- docs/core/proto-docs.md
- x/auth/simulation/genesis.go
- x/auth/types/account.go
- x/auth/types/account_test.go
- x/auth/vesting/types/vesting_account.go
- x/distribution/keeper/hooks.go
- x/distribution/types/keys.go
- x/params/types/subspace.go
- x/params/types/subspace_test.go
- x/params/types/table.go
- x/slashing/keeper/hooks.go
- Deleted comment from race test of `test.yml` github action
- Enabled sim test
- I fixed some bug from the sim test failures
- don't `GetConsensusParams()` while initializing `checkState`. Reverts a part of https://github.com/line/lbm-sdk/pull/142.
- use random valid sig block period over 100 for sim testing
- modify `BaseAccount` marshal/unmarshal
- add `BaseVestingAccount`, `ContinuousVestingAccount`, `PeriodicVestingAccount` and `DelayedVestingAccount` marshalJSONPB/unmarshalJSONPB
- `x/distribution/keeper/hooks.go` address conversion bug
- `x/distribution/types/keys.go` key prefix bug
- remove param cache: this is a bug. Several `Set`s and no `Write` make the mismatch between db store and cache. Reverts https://github.com/line/lbm-sdk/pull/198
- `x/slashing/keeper/hooks.go` address …
> test: enable sim test, race test

- README.md
- init_node.sh
update init_node.sh and README.md file for local multi node test
closes: #XXXX
---
> chore: local multi node test setting files

- go.mod
- go.sum
bump up wasmvm to v0.14.0-0.8.0
The version includes an option to link libwasmvm statically.
---
> build(wasm): bump up wasmvm to v0.14.0-0.8.0

- x/auth/simulation/genesis.go
rc0/v0.1.0 branch failed on `test-sim-multi-seed-long` because too small sig block height for long block length(500).
I increase minimum limit of randomly generated sig block period for sim test.
> fix: increate minimum limit of randomly generated sig block period

- .github/workflows/release-sims.yml
- Makefile
`Github action job execution time - Each job in a workflow can run for up to 6 hours of execution time. If a job reaches this limit, the job is terminated and fails to complete.` from https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration.
Existing  `test-sim-multi-seed-long` test takes over 6 hours, so it failed because of github action timeout.
So I split this test into 3 parts.
---
> test: split long sim test into 3 parts

- .github/workflows/sims.yml
- CHANGELOG.md
- RELEASE_CHANGELOG.md
- x/bank/client/cli/query.go
- x/bank/keeper/grpc_query.go
- x/bank/keeper/grpc_query_test.go
> fix: check bech32 address format in bank query

- .github/workflows/autopr.yml
- .github/workflows/release-sims.yml
- .github/workflows/sims.yml
- CHANGELOG.md
- RELEASE_CHANGELOG.md
- x/bank/client/cli/query.go
- x/bank/keeper/grpc_query.go
- x/bank/keeper/grpc_query_test.go
> fix: merge release patch

- x/distribution/client/cli/tx.go
- x/distribution/client/cli/tx_test.go
If cli tx withdraw-all-rewards sends empty tx, the tx would be
rejected by validators because it has no msgs. However, the cli sends
empty tx only if one sets `--max-msgs=0` which means it does not split
the msgs. When you set `max-msgs` with any positive number, the cli
does not send any tx, which may confuse you because you cannot get the
feedback indicating the address has no delegations.
This patch addresses the problem, by forcing genOrBroadcastFn when the
number of total msgs generated is zero. It will provide the same user
experience with any `max-msgs`.
closes: #363 
---
> fix: force genOrBroadcastFn even when max-msgs != 0

- x/wasm/keeper/keeper.go
- x/wasm/keeper/metrics.go
- x/wasm/keeper/options.go
closes: #357
The metrics method for observing the wasm was the telemetry.
However, telemetry had performance degradation issues.
Change the method to use prometheus directly. In testing, this did not cause any performance degradation.
In addition to telemetry, wasm already had prometheus metrics for observing the cache of the VM internal implementation.
However, the observation method between our need and exist cache metrics is different .
Existing cache metrics are periodic observation by subscription of prometheus collector,
What we want is to happen at a point in time that run.
So add a new structure without refactoring the existing cache metrics.
---
checked off. If any of the checklist items are not …
> feat: change wasm metrics method

- CHANGELOG.md
- x/feegrant/types/filtered_fee.go
- x/feegrant/types/filtered_fee_test.go
By the fix, AllowedMsgAllowance updates its allowance after the change in `Accept()`.
To catch the corresponding issue, the fix also adds new unit tests.
closes: #382 
---
> fix: update allowance inside AllowedMsgAllowance

- CHANGELOG.md
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
Fix a bug that failed to generate `swagger.yaml`
Wasm path was wrong. 
---
> chore: fix swagger's config path for wasm

- CHANGELOG.md
- go.mod
- go.sum
Apply https://github.com/line/tm-db/pull/33.
closes: #314 
---
> fix: fix invalid root hash by bumping up tm-db

- CHANGELOG.md
- x/wasm/types/codec.go
Wasm APIs does not work, because the service Msg interface did not registered in the codec.
* `StoreCodeAndInstantiateContract`
* `UpdateContractStatus`
* `UpdateContractStatusProposal`
```
Error: unable to resolve type URL /lbm.wasm.v1.MsgStoreCodeAndInstantiateContract
```
---
> fix: fix bug where `StoreCodeAndInstantiateContract`, `UpdateContractStatus`, `UpdateContractStatusProposal` API does not work

- cosmovisor/go.mod
- cosmovisor/go.sum
The version of the xz module(used in cosmovisor) has been raised from 0.5.5 to 0.5.10, due to a security alert.
closes: #XXXX
---
> build(deps): github.com/ulikunitz/xz from 0.5.5 to 0.5.10

- CHANGELOG.md
- docs/core/proto-docs.md
- proto/lbm/consortium/v1/query.proto
- testutil/rest/rest.go
- x/consortium/client/cli/query.go
- x/consortium/client/cli/tx.go
- x/consortium/client/proposal_handler.go
- x/consortium/client/testutil/cli_test.go
- x/consortium/client/testutil/grpc.go
- x/consortium/client/testutil/query.go
- x/consortium/client/testutil/suite.go
- x/consortium/client/testutil/tx.go
- x/consortium/keeper/grpc_query.go
- x/consortium/keeper/grpc_query_test.go
- x/consortium/keeper/keeper_test.go
- x/consortium/keeper/validator_test.go
- x/consortium/module.go
- x/consortium/types/proposal.go
- x/consortium/types/query.pb.go
- x/consortium/types/query.pb.gw.go
I intended to add tests to the module, but I have found & fixed a bug along the way.
---
> fix: validate validator addresses in update-validator-auths proposal

- CHANGELOG.md
- RELEASE_CHANGELOG.md
Release 0.44.0-rc0
* (feat) [\#352] (https://github.com/line/lbm-sdk/pull/352) iavl, db & disk stats logging
* (x/gov) [\#368](https://github.com/line/lbm-sdk/pull/368) Governance Split Votes, use `MsgWeightedVote` to send a split vote. Sending a regular `MsgVote` will convert the underlying vote option into a weighted vote with weight 1.
* (x/upgrade) [\#377] (https://github.com/line/lbm-sdk/pull/377) To smoothen the update to the latest stable release, the SDK includes vesion map for managing migrations between SDK versions.
* (x/wasm) [\#358] (https://github.com/line/lbm-sdk/pull/358) change wasm metrics method to using prometheus directly
* (x/feegrant) [\#380] (https://github.com/line/lbm-sdk/pull/380) Feegrant module
* (x/wasm) [\#395] (https://github.com/line/lbm-sdk/pull/395) Add …
> docs: release 0.44.0-rc0

- CHANGELOG.md
- RELEASE_CHANGELOG.md
Release 0.45.0-rc0
* (x/wasm) [\#444](https://github.com/line/lbm-sdk/pull/444) Merge wasmd 0.19.0
* remove custom encoder from x/wasm/keeper.NewKeeper's arg. After the Token/collection module is added, it will be ported again.
* (cosmos-sdk) [\#437](https://github.com/line/lbm-sdk/pull/437) dump up to cosmos-sdk v0.42.11
* [changelog of cosmos-sdk v0.42.11](https://github.com/cosmos/cosmos-sdk/blob/v0.42.11/CHANGELOG.md)
* (feat) [\#434](https://github.com/line/lbm-sdk/pull/434) Revert signature mechanism using `sig_block_height`
* (x/token) [\#416](https://github.com/line/lbm-sdk/pull/416) Migrate token module from line/link
* (x/wasm) [\#436](https://github.com/line/lbm-sdk/pull/436) remove `x/wasm/linkwasmd`
* (makefile, ci) [\#438](https://github.com/line/lbm-sdk/pull/438) fix `make …
> chore: release 0.45.0-rc0

- .github/actions/generate-swagger/action.yml
- .github/workflows/proto.yml
- CHANGELOG.md
- proto/lbm/consortium/v1/query.proto
Checks swagger related generated files are in sync.
closes: #456 
#456 
Push a commit in which the generated files are out of sync, and confirm whether the CI catches it.
And push the revert and confirm it passes.
> ci: add swagger check

- .github/workflows/docker.yml
- CHANGELOG.md
- Dockerfile
It makes CI to publish the docker image on tag pushes.
It adds a workflow which publishes the docker image on tag push event.
The destination is docker.io/line/lbm-simapp for now.
The image tag would be the corresponding semver and `latest`.
closes: #455 
Refer to #455
The PR will trigger the workflow. And I confirmed it works, I will revert the commit which triggers the workflow on PR.
> ci: publish docker image on tag push

- CHANGELOG.md
- client/config/config.go
- client/config/toml.go
It fixes the confusing behavior discussed in #473.
It's not a bug, but we concluded not to set the default value on the output format in the config file.
closes: #473
#473 
Executed tx cli and confirmed the output is in json.
Also confirmed the output of query cli is in yaml.
Tested on Docker image, on Debian bookworm.
> fix: change the default value of the client output format in the config

- CHANGELOG.md
- x/README.md
- x/stakingplus/spec/01_state.md
- x/stakingplus/spec/02_state_transitions.md
- x/stakingplus/spec/03_messages.md
- x/stakingplus/spec/04_begin_block.md
- x/stakingplus/spec/05_end_block.md
- x/stakingplus/spec/06_hooks.md
- x/stakingplus/spec/07_events.md
- x/stakingplus/spec/08_params.md
- x/stakingplus/spec/README.md
> docs: update documents on x/stakingplus

- init_node.sh
fix init_node.sh for grpc-web port(added by #468)
closes: #XXXX
> chore: fix init_node script(grpc-web port)

- CHANGELOG.md
- server/grpc/server_test.go
After bumping up to cosmos-sdk@0.45.1, errors frequently occur in the data race. in the process of work
I deleted the build tag for debugging, but it seems that an error like this occurred because it was not restored. 
I restored the build tag because the test code in server/grpc did not take the data race into account.
closes: #514
> fix: restore norace tag

- .mergify.yml
Many dependencies pr is added but it is not check and merged. 
So, I think we need to use mergify which merge automatic if the following condition is satisfied.
The condition
* 2 approve
* automerge label
* pass CI
Passing CI must be necessary but the option which all checks have passed is not exist in Mergify options. So the reviewer should to check all checks have passed.
> ci: change automerge conditions of Mergify

- CHANGELOG.md
- baseapp/block_gas_test.go
- x/auth/keeper/keeper.go
- x/auth/types/account.go
- x/auth/types/account_test.go
- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
- x/bank/keeper/keeper.go
- x/bank/keeper/send.go
- x/wasm/keeper/keeper_test.go
I restored the part(MarshalX, UnmarshalX) that was removed due to a build failure while bumping up to cosmos-sdk@v0.45.1.
wrong format
```json
{
"@type": "/lbm.auth.v1.BaseAccount",
"account_number": "0",
"address": "link146asaycmtydq45kxc8evntqfgepagygelel00h",
"ed25519_pub_key": null,
"multisig_pub_key": null,
"secp256k1_pub_key": {
"key": "AgT2QPS4Eu6M+cfHeba+3tumsM/hNEBGdM7nRojSZRjF"
},
"secp256r1_pub_key": null,
"sequence": "1"
},
```
right format
```json
{
"@type": "/lbm.auth.v1.BaseAccount",
"account_number": 0,
"address": "link146asaycmtydq45kxc8evntqfgepagygelel00h",
"pub_key": {
"key": "eyJrZXkiOiJBZ1QyUVBTNEV1Nk0rY2ZIZWJhKzN0dW1zTS9oTkVCR2RNN25Sb2pTWlJqRiJ9",
"type": 1
},
"sequence": "1"
},
```
closes: #515
> fix: genesis auth account format

- CHANGELOG.md
- x/foundation/authz_test.go
- x/foundation/foundation.go
- x/foundation/foundation_test.go
- x/foundation/genesis.go
- x/foundation/genesis_test.go
- x/foundation/keeper/genesis_test.go
- x/foundation/keeper/member_test.go
- x/foundation/keeper/proposal.go
- x/foundation/keeper/proposal_test.go
- x/foundation/keeper/tally.go
- x/foundation/keeper/vote_test.go
- x/foundation/module/module.go
This patch fixes bugs on x/foundation:
1. fix unpacking of the foundation info.
2. support abstain option (where the policy is percentage type).
> fix: fix genesis and support abstain

- CHANGELOG.md
- x/auth/types/account.go
- x/auth/types/account_test.go
Fixed unmarshal error if  account_number of genesis auth's account is string type when load the genesis file
> fix: fix unmarshal bug of BaseAccountJSON.

- CHANGELOG.md
- client/query_test.go
Signed-off-by: zemyblue <zemyblue@gmail.com>
This data race problem of `TestQueryABCIHeight` occurs frequently. 
There are three times test continually in `TestQueryABCIHeight`. In the last test, he origin expected block height is 4, but sometimes the test result is 5. I think this reason is that the block confirm time is very short(1s) and it seems to be affected by previous tests and CI system spec. So, increase the expected value by 1 and modify the test to succeed if the block height is below that value. 
related: #514
> fix: fix the data race problem in `TestQueryABCIHeight`

- .github/workflows/docker.yml
- CHANGELOG.md
- Dockerfile
- go.mod
- go.sum
- init_node.sh
Signed-off-by: zemyblue <zemyblue@gmail.com>
The registered docker image of docker hub is not executed in Apple M1 Macbook. Because the docker image was not built with the `platforms` information, so I fix this problem in this PR. 
And `libstdc++` library is required for `linux/amd64` because `bls-eth-go-binary` of `ostracon`. So I add it in the `Dockerfile`.
> fix: push docker image action.

- x/wasm/client/cli/genesis_msg.go
I found that the error message contained an unnecessary string.
I have already pushed the PR to the forking source.
https://github.com/CosmWasm/wasmd/pull/899
> fix: remove unnecessary string

- CHANGELOG.md
- server/grpc/server_test.go
- types/grpc/headers.go
Revert gRPC block height header.
`x-lbm-block-height` -> `x-cosmos-block-height`
I think no need to keep the `x-lbm-block-height`.
> chore: revert gRPC block height header.

- CHANGELOG.md
- docs/core/event.md
- x/bank/spec/04_events.md
- x/collection/spec/03_events.md
- x/crisis/spec/03_events.md
- x/distribution/spec/06_events.md
- x/evidence/spec/04_events.md
- x/feegrant/spec/04_events.md
- x/foundation/spec/03_events.md
- x/gov/spec/04_events.md
- x/slashing/spec/06_events.md
- x/staking/spec/07_events.md
- x/token/spec/03_events.md
Update outdated documentation about the events.
It also adds common specification about the events.
> docs: update outdated events in specs

- CHANGELOG.md
- simapp/app.go
I added iterator feature for simapp
> chore: add iterator feature

- CHANGELOG.md
- x/auth/vesting/types/codec.go
- x/authz/codec.go
- x/bank/keeper/send.go
- x/genutil/client/cli/migrate.go
- x/genutil/client/testutil/migrate.go
- x/genutil/types/types.go
- x/params/keeper/keeper.go
* fix missing changes of #600 
* remove unnecessary function(`ChangeBlockedAddrState`) in bank module
* fit the `VersionMap` of `genutil` module to be same with other module's property name 
* change `Keeper.space` type to be same with cosmos-sdk
In the #549 , we changed the difference with cosmos-sdk. But there are some minor things that haven't been fixed..
> chore: change some minor things that haven't been fixed in #549

- CHANGELOG.md
- x/collection/keeper/grpc_query.go
This patch addresses the following issues on x/collection:
- Query/Balance panics where the returning balance is zero.
- The validation logic and the corresponding errors resemble that of the cosmos-sdk x/bank, not that of daphne.
> fix: make x/collection Query/Balance not to panic on amount of zero in return

- CHANGELOG.md
- x/collection/collection.go
- x/collection/collection_test.go
- x/collection/keeper/msg_server.go
- x/collection/keeper/supply.go
- x/collection/keeper/supply_test.go
This patch addresses the following issues:
- MsgModify updates the corresponding value of the attribute with the key, not with the value.
- MsgModify updates unintended attribute.
> fix: fix bugs in x/collection MsgModify

- CHANGELOG.md
- simapp/app.go
- simapp/test_access.go
- simapp/test_helpers.go
- x/ibc/testing/chain.go
- x/wasm/keeper/snapshotter.go
- x/wasm/keeper/snapshotter_integration_test.go
I have added the snapshotter feature which was activated by the version up of the cosmos-sdk.
I did not cherry-pick, but copied and added the original repository.
See below for implementation
snapshotter
https://github.com/CosmWasm/wasmd/blob/v0.27.0/x/wasm/keeper/snapshotter.go
test
https://github.com/CosmWasm/wasmd/blob/v0.27.0/x/wasm/keeper/snapshotter_integration_test.go
app
https://github.com/CosmWasm/wasmd/blob/v0.27.0/app/app.go#L743-L750
closes: #634
> fix: wasm module's FIXME in the snapshotter.go file

- CHANGELOG.md
- x/wasm/keeper/api.go
Adjust gas cost of GetContractEnv following the benchmark.
> fix: adjust gas cost for GetContractEnv of CosmWasmAPI

- CHANGELOG.md
- server/config/config.go
- server/config/toml.go
- server/start.go
remove bech32-cache-size from config.toml
closes: #664
> feat: remove bech32-cache-size

- CHANGELOG.md
- server/config/toml.go
- simapp/simd/cmd/root.go
- store/iavl/store.go
Fix the bug not setting `iavl-cache-size` value of `app.toml` of simapp
And change `DefaultIAVLCacheSize`  to 1024 * 512.
Because the iavl cache size is just one store's iavl cache size and each modules have itself's store. if the all module's store use iavl type, the default all iavl cache size is very big. So I change default size to a little small size. 
related: #666, #675
> fix the bug not setting `iavl-cache-size` value of `app.toml`

- .github/workflows/release-sims.yml
- CHANGELOG.md
- baseapp/abci.go
- baseapp/abci_test.go
- baseapp/baseapp.go
- x/auth/ante/setup.go
- x/auth/ante/setup_test.go
This patch fixes bugs relevant to #48. We should revisit this and #48. Please refer to tendermint/tendermint#6740.
Related: line/ostracon#158
> fix: fix max gas validation

- CHANGELOG.md
- x/foundation/config.go
- x/foundation/foundation.go
- x/foundation/foundation_test.go
- x/foundation/keeper/genesis.go
- x/foundation/keeper/genesis_test.go
- x/foundation/keeper/keeper_test.go
- x/foundation/keeper/member_test.go
- x/foundation/keeper/msg_server_test.go
Remove the minimum boundary of the policies:
- `MinThreshold`
- `MinPercentage`
After this patch is applied, we could out-source the proposal relevant logic to `x/group` later.
> refactor: remove `MinThreshold` and `MinPercentage` from x/foundation config

- CHANGELOG.md
- x/foundation/keeper/exec_test.go
- x/foundation/keeper/keeper_test.go
- x/foundation/keeper/msg_server_test.go
- x/foundation/keeper/proposal.go
- x/foundation/keeper/proposal_test.go
- x/foundation/keeper/vote_test.go
- x/foundation/msgs_test.go
This patch will fix the stopping logic in the iteration of the `abortOldProposals()`, and add the corresponding unit test.
It also fixes the misleading variable names of proposal in the test.
It didn't update the state of the latest proposals (to aborted), if there are proposals of multiple foundation versions.
> fix: fix bugs on aborting x/foundation proposals

- CHANGELOG.md
- x/bank/keeper/genesis_test.go
- x/bankplus/keeper/keeper.go
- x/bankplus/keeper/keeper_test.go
- x/ibc/applications/transfer/keeper/relay_test.go
closes: #667 
Add missing blockedAddr checking feature in `bankplug` module. 
Thank you. @ulbqb
> chore: add missing blockedAddr checking in bankplus

- client/grpc/tmservice/service.go
- client/grpc/tmservice/service_test.go
- client/rpc/block.go
- client/rpc/routes.go
- client/rpc/rpc_test.go
- go.mod
- go.sum
relates: #699
* Fix TODO: use **base64.URLEncoding** to modify TestQueryBlockByHash
* https://github.com/line/lbm-sdk/blob/289ca6b2d11f988d6d45e28edf691511d2764209/client/grpc/tmservice/service_test.go
* When **_base64.StdEncoding_** use "/", it happens to find other REST path and "501 Not Implements"
* Fix typo
* Add the same feature on RPC
I found out how to fix TODO
By unit test code
> fix: TODO: use base64.URLEncoding to modify TestQueryBlockByHash

- CHANGELOG.md
- client/tx/tx.go
- client/tx/tx_test.go
- x/auth/client/testutil/suite.go
In the current multi sign tx, if there is even one direct mode sign, the sign will fail. 
It changed to allows one direct sign even multi sign tx .
ref. https://github.com/cosmos/cosmos-sdk/pull/10683/files
closes: #XXXX
> fix: allow up to one direct sign in multi sign tx

- CHANGELOG.md
- x/foundation/keeper/abci_test.go
- x/foundation/keeper/keys.go
- x/foundation/keeper/proposal.go
This patch will fix `EndBlocker()` of `x/foundation` and add the corresponding unit tests.
> fix: fix x/foundation EndBlocker

- CHANGELOG.md
- go.sum
- x/bank/keeper/keeper.go
- x/bank/types/key.go
Make DenomMetadata substore only with DenomMetadataPrefix
closes: #714
> refactor: remove useless DenomMetadata key function

- CHANGELOG.md
- x/staking/types/authz.go
- x/staking/types/authz_test.go
Currently, only one of AllowedList and DenyList can be set in the structure of StakeAuthorization.
There is a structural problem that causes Accept func to always fail when DenyList is set.
Check the size of the AllowedList together with the isValidatorExists check.
ref. https://github.com/cosmos/cosmos-sdk/issues/11391
closes: #725
> fix: check allowedList size in StakeAuthorization.Accept

- CHANGELOG.md
- crypto/ledger/ledger_secp256k1.go
`VRFProve()` function was incorrect implementation and unnecessary. So, I removed `VRFProve()` function.
> fix: remove `VRFProve`

- CHANGELOG.md
- x/foundation/keeper/abci_test.go
- x/foundation/keeper/proposal.go
The specification #721 says aborted and withdrawn proposals must be pruned at their voting period end. This patch addresses the difference in logic from the documentation's.
> fix: prune stale x/foundation proposals at voting period end

- CHANGELOG.md
- x/foundation/README.md
Added `govmint` to `x/foundation` specification doc.
closes: #739
> docs: add govmint to x/foundation specification

- CHANGELOG.md
- simapp/app.go
- x/bank/keeper/genesis_test.go
- x/bank/simulation/operations_test.go
> fix: add x/distribution's module account into blockedAddr

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/baseapp_test.go
- baseapp/options.go
- server/config/config.go
- server/config/toml.go
- server/start.go
- simapp/simd/cmd/root.go
Change to create `chCheckTx` with the value set in app config.
Basically, `chCheckTx` of BaseApp should be equals to or greater than mempool size. 
But when running NewBaseApp, the mempool size can not know.
So I add the feature set the size of `chCheckTx` as config
So following features have been changed
* add `chCheckTxSize` in Baseapp
* add `FlagChanCheckTxSize` flag as cmd flag
* add `chan-check-tx-size` field in app config.
* set default `chanCheckTxSize` to 10000.
closes: #753
> feat: change to create `chCheckTx` with the value set in app config.

- CHANGELOG.md
- x/auth/client/cli/tx_sign.go
- x/auth/client/testutil/suite.go
Get sequence number for non-multisig signing in batch-sign
closes: #755
> fix: get seq number for non-multisig signing

- CHANGELOG.md
- simapp/app.go
- x/foundation/client/testutil/grpc.go
- x/foundation/client/testutil/query.go
- x/foundation/client/testutil/suite.go
- x/foundation/keeper/invariants.go
- x/foundation/keeper/invariants_test.go
- x/foundation/keeper/msg_server_test.go
- x/foundation/module/module.go
- x/foundation/msgs_test.go
This patch will add following invariants to x/foundation:
- ModuleAccountInvariant
- It checks whether each balances of the module accounts is in a sane state.
- "treasury": It must be equal to the corresponding value in the pool.
- TotalWeightInvariant
- It checks whether the total weight is in a sane state.
- Each weight of the member is implicitly one, hence the weight must be equal to the number of the members.
- ProposalInvariant
- It checks whether each proposal is in a sane state.
- Old proposals must have been aborted, so they must not be in the submitted state.
> feat: add invariants to x/foundation

- CHANGELOG.md
- server/api/server.go
- server/start.go
> fix: start telemetry independently from the API server

- CHANGELOG.md
- x/foundation/client/testutil/cli_test.go
Restores the removeed `build norace` flag.
ref. #709 
closes: #762
> fix: restore build norace flag

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (x/ibc) [\#651](https://github.com/line/lbm-sdk/pull/651) feat: update x/ibc to support github.com/cosmos/ibc-go@v3.0.0
* (x/foundation) [\#709](https://github.com/line/lbm-sdk/pull/709) add `gov mint` for x/foundation proposal
* (iavl) [\#738](https://github.com/line/lbm-sdk/pull/738) bump github.com/cosmos/iavl from v0.17.3 to v0.19.3
* (baseapp) [\#756](https://github.com/line/lbm-sdk/pull/756) Change to create chCheckTx with the value set in app config
* (x/foundation) [\#758](https://github.com/line/lbm-sdk/pull/758) add invariants to x/foundation
* (refactor) [\#685](https://github.com/line/lbm-sdk/pull/685) remove x/foundation UpdateValidatorAuthsProposal
* (x/foundation) [\#686](https://github.com/line/lbm-sdk/pull/686) remove `Minthreshold` and `MinPercentage` from x/foundation …
> docs: release 0.45.0-rc9

- CHANGELOG.md
- x/foundation/README.md
There was a duplicate `[proposers-json]' in the command description of submit-proposal, so it was removed.
closes: #XXXX
> docs: fix submit-proposal tx command

- CHANGELOG.md
- x/foundation/keeper/genesis.go
- x/foundation/keeper/genesis_test.go
This patch will add a logic to export the x/foundation's pool.
> fix: export x/foundation pool

- CHANGELOG.md
- x/foundation/client/cli/tx.go
This patch will guide users to use the generate-only flag in following commands:
- MsgUpdateParams
- MsgWithdrawFromTreasury
- MsgUpdateMembers
- MsgUpdateDecisionPolicy
- MsgGrant
- MsgRevoke
- MsgGovMint
> fix: guide users to use generate only in messages for x/foundation authority

- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release-sims.yml
- .github/workflows/sims.yml
- .github/workflows/test.yml
- CHANGELOG.md
closed: #771 
* Change the `release-sims` test trigger rule when add `release` tag.
* Add github action in `rc*/*` and `release/*` branches like `main` branch
The `release-sims` test of ci take too many times, and there is alternative short test. So I think it is no need to test every PR.
> ci: change github action trigger rules for `release/*` and `rc*/*` branches

- CHANGELOG.md
- baseapp/abci.go
* Implemented method `SetOption()`
> chore: implemented method `SetOption()`

- CHANGELOG.md
- baseapp/grpcserver.go
- init_node.sh
- server/start.go
- server/util.go
- x/auth/client/rest/query.go
- x/bank/client/cli/tx.go
- x/feegrant/client/cli/tx.go
- x/foundation/keeper/member.go
- x/slashing/genesis.go
- x/slashing/keeper/hooks.go
- x/staking/genesis.go
- x/staking/keeper/msg_server.go
- x/wasm/client/cli/query.go
* baseapp/grpcserver.go
* grpc.SetHeader(grpcCtx, md)
* server/start.go
* serverCtx.Viper.BindPFlags(cmd.Flags())
* server/util.go
* serverCtx.Viper.BindPFlags(cmd.Flags())
*  serverCtx.Viper.BindPFlags(cmd.PersistentFlags())
* x/auth/client/rest/query.go
*  packStdTxResponse(w, clientCtx, txRes)
* x/bank/client/cli/tx.go
* cmd.Flags().Set(flags.FlagFrom, args[0])
* x/feegrant/client/cli/tx.go
* cmd.Flags().Set(flags.FlagFrom, args[0])
* x/foundation/keeper/member.go
*  info.SetDecisionPolicy(policy)
* x/slashing/genesis.go
* keeper.AddPubkey(ctx, consPk)
* x/slashing/keeper/hooks.go
* keeper.AddPubkey(ctx, consPk)
* x/staking/genesis.go
* keeper.SetValidatorByConsAddr(ctx, validator)
* x/staking/keeper/msg_server.go
* k.SetValidatorByConsAddr(ctx, validator)
* x/wasm/client/cli/query.go …
> fix: add unhandled return error handling.

- .github/workflows/test.yml
- .gitignore
- .gitmodules
- CHANGELOG.md
- Makefile
This PR enable to use libsodium version ostracon. We can use libsodium version ostracon by the following command.
```bash
$ LBM_BUILD_OPTIONS=libsodium make install      
```
> feat: enable to use libsodium version ostracon

- CHANGELOG.md
- x/collection/keeper/supply.go
- x/collection/keeper/supply_test.go
- x/token/keeper/supply_test.go
> fix: fix x/collection ModifyContract

- .github/workflows/test.yml
- CHANGELOG.md
This PR has following changes.
- add test.yml to diff target in test.yml
- add step to install libsodium
related: #801
Even if ci test is changed, the test is skipped. I missed that it had to install libsodium because of that.
> fix: fix test flow to install libsodium

- CHANGELOG.md
- x/foundation/README.md
- x/foundation/client/cli/tx.go
This patch would update the x/foundation documentation.
It would:
- Update the references in README.md
- Update the descriptions in CLIs.
> docs: update x/foundation documentation

- CHANGELOG.md
- RELEASE_CHANGELOG.md
This version based on cosmos-sdk v0.45.10 and Ostracon v1.0.7.
* (global) [\#783](https://github.com/line/lbm-sdk/pull/783) bump up github.com/cosmos/cosmos-sdk to v0.45.10
* (build) [\#793](https://github.com/line/lbm-sdk/pull/793) enable to use libsodium version ostracon
* (x/auth) [\#776](https://github.com/line/lbm-sdk/pull/776) remove unused MsgEmpty
* (x/foundation) [\#772](https://github.com/line/lbm-sdk/pull/772) export x/foundation pool
* (baseapp) [\#781](https://github.com/line/lbm-sdk/pull/781) implement method `SetOption()` in baseapp
* (global) [\#782](https://github.com/line/lbm-sdk/pull/782) add unhandled return error handling
* (x/collection,x/token) [\#798](https://github.com/line/lbm-sdk/pull/798) Fix x/collection ModifyContract
* (ci) …
> docs: release v0.46.0-rc10

- CHANGELOG.md
- RELEASE_CHANGELOG.md
This version based on cosmos-sdk v0.45.10, wasmd v0.27.0 and Ostracon v1.0.7.
* (global) [\#783](https://github.com/line/lbm-sdk/pull/783) bump up github.com/cosmos/cosmos-sdk to v0.45.10
* (build) [\#793](https://github.com/line/lbm-sdk/pull/793) enable to use libsodium version ostracon
* (x/wasm) [\#570](https://github.com/line/lbm-sdk/pull/570) Merge wasmd 0.27.0
* (x/wasm) [\#470](https://github.com/line/lbm-sdk/pull/470) remove contract activation control by actor
* (x/wasm) [\#513](https://github.com/line/lbm-sdk/pull/513) fix message representation for signing
* (x/foundation) [\#518](https://github.com/line/lbm-sdk/pull/518) add foundation treasury feature to x/foundation
* (x/foundation) [\#528](https://github.com/line/lbm-sdk/pull/528) add a feature of whitelist for …
> Release lbm-sdk v0.46.0

- CHANGELOG.md
- x/auth/types/codec.go
- x/auth/vesting/types/codec.go
- x/authz/codec.go
- x/bank/types/codec.go
- x/collection/codec.go
- x/crisis/types/codec.go
- x/distribution/types/codec.go
- x/evidence/types/codec.go
- x/feegrant/codec.go
- x/foundation/codec.go
- x/foundation/codec/cdc.go
- x/foundation/msgs.go
- x/gov/types/codec.go
- x/slashing/types/codec.go
- x/staking/types/codec.go
- x/stakingplus/codec.go
- x/token/codec.go
- x/upgrade/types/codec.go
- x/wasm/lbmtypes/codec.go
- x/wasm/types/codec.go
Same PR as cosmos/cosmos-sdk#13196, but for foundation's MsgSubmitProposal.
> fix!: Fix foundation amino codec

- CHANGELOG.md
- go.mod
- go.sum
- x/wasm/dynamic_link_test.go
- x/wasm/keeper/api.go
- x/wasm/keeper/api_test.go
- x/wasm/keeper/bench_test.go
- x/wasm/keeper/keeper_test.go
- x/wasm/keeper/test_common.go
- x/wasm/simulation/operations.go
- x/wasm/types/types.go
This PR makes GetContractEnv wasm API for x/wasm able to calculate instantiate cost. This function uses the input length in the calculation, so this PR adds it and arg for return as new args of the GetContractEnv.
This is used for costing instantiate cost to callings of dynamic functions (https://github.com/line/cosmwasm/issues/257). It also works as the limit of the length of inputs of callings of dynamic functions.
This PR modifies some unit tests.
> feat: add calculate instantiate cost function into get contract env api

- x/bankplus/keeper/keeper_test.go
closes: #XXXX
ref. https://github.com/line/lbm-sdk/pull/876#issuecomment-1418530769
> chore: modify error case

- CHANGELOG.md
- go.mod
> build: retract v1.0.0

- CHANGELOG.md
- client/broadcast.go
- client/broadcast_test.go
lbm-sdk needs to be mapped for new errors in ostracon([ErrTxInMap](https://github.com/line/ostracon/blob/v1.0.8/mempool/errors.go#L10)).
For this error, lbm-sdk maps errors in [types/errors/errors.go](https://github.com/line/lbm-sdk/blob/main/types/errors/errors.go) to make it easier for users to handle.
An implementation concern is whether ErrInTxMempoolCache fully explains this error.
- For cosmos-sdk compatibility and lbm-sdk interface retention
- "ErrInTxMempoolCache" is insufficient, but the message "tx already in mempool" is enough to explain
For this reason, I mapped it to ErrTxInMempoolCache, but I think renaming this error to ErrTxInMempool is also a way.
closes: #810
> Map Ostracon:ErrTxInMap to lbm-sdk:ErrTxInMempoolCache

- CHANGELOG.md
- x/collection/client/testutil/suite.go
- x/collection/genesis.go
- x/collection/keeper/genesis.go
- x/collection/keeper/keeper_test.go
- x/collection/keeper/msg_server_test.go
- x/collection/keeper/nft_test.go
- x/collection/keeper/param.go
This patch would change the default value of `DepthLimit` and `WidthLimit` of x/collection, which constrains the size of hierarchies of composable nfts on x/collection.
Business requirement.
> fix: change the default params of x/collection

- CHANGELOG.md
- baseapp/abci.go
- x/auth/ante/setup.go
- x/auth/ante/setup_test.go
> fix: remove max gas validation

- CHANGELOG.md
- client/docs/config.json
- client/docs/swagger-ui/swagger.yaml
*  fix the bug that wasn't added `lbm.tx.v1beta1.Service/GetBlockWithTxs` in swagger
* Bug not added in #891.
> fix: fix a bug not added `lbm.tx.v1beta1.Service/GetBlockWithTxs` in swagger

- .github/workflows/tag.yml
- .goreleaser.yml
- CHANGELOG.md
- Dockerfile
- Makefile
- simapp/simd/cmd/root.go
- simapp/test_helpers.go
> build: update release pipeline to match non-wasm env

- CHANGELOG.md
- x/collection/client/cli/tx.go
* Fix: add missing tx cmd for cli
> fix: add missing Command(collection module's TxCmdModify)

- CHANGELOG.md
- x/foundation/keeper/exec.go
This patch would propagate events correctly to the current context.
The `x/foundation` module does not propagate events correctly to the current context on its `MsgExec`.
The corresponding bug has been already fixed in the upstream.
> fix: propagate events in x/foundation through sdk.Results

- CHANGELOG.md
- docs/core/proto-docs.md
- proto/lbm/collection/v1/event.proto
- proto/lbm/token/v1/event.proto
- x/collection/event.pb.go
- x/token/event.pb.go
This patch would update the comments relevant to the changes in PR #900.
> docs: update comments in the x/token,collection events proto

- CHANGELOG.md
- x/foundation/keeper/params.go
This patch would fix nondeterministic execution in x/foundation Msg/UpdateParams.
10 Msg/UpdateParams tests in row, on the network with 8 nodes.
> fix: sort removed urls in x/foundation Msg/UpdateParams

- CHANGELOG.md
- x/foundation/expected_keepers.go
- x/foundation/keeper/internal/abci.go
- x/foundation/keeper/internal/abci_test.go
- x/foundation/keeper/internal/keeper_test.go
- x/foundation/keeper/internal/treasury.go
- x/foundation/keeper/internal/treasury_test.go
This patch would truncate the tax before updating its own pool, ensuring the corresponding balance and the pool are in sync.
> fix: fix broken x/foundation invariant on treasury

- CHANGELOG.md
- x/collection/keeper/grpc_query.go
- x/collection/keeper/grpc_query_test.go
This patch would allow zero amount of coin in x/collection Query/Balance.
> fix: allow zero amount of coin in x/collection Query/Balance

- CHANGELOG.md
- x/collection/keeper/supply.go
This patch would remove duplicated events in x/collection Msg/Modify.
> fix: remove duplicated events in x/collection Msg/Modify

- CHANGELOG.md
- docs/core/proto-docs.md
- proto/lbm/collection/v1/query.proto
- x/collection/keeper/grpc_query.go
- x/collection/keeper/grpc_query_test.go
- x/collection/query.pb.go
This patch would make Query/Parent not to return an error even if the parent does not exist.
Daphne compatibility.
> fix: return nil where the parent not exists in x/collection Query/Parent

- CHANGELOG.md
- simapp/app.go
- x/collection/client/testutil/query.go
- x/collection/expected_keepers.go
- x/collection/keeper/grpc_query.go
- x/collection/keeper/grpc_query_test.go
- x/collection/keeper/keeper_test.go
- x/collection/module/module.go
- x/token/expected_keepers.go
- x/token/keeper/grpc_query.go
- x/token/keeper/grpc_query_test.go
- x/token/keeper/keeper_test.go
- x/token/module/module.go
This patch would replace previous errors on queries into gRPC ones.
"Almost" all gRPC queries on x/token and x/collection would return NotFound, where
- The relevant address does not exist
- The relevant contract does not exist
- The relevant token does not exist
- The relevant token class does not exist
CAUTION: this will break the compatibility with Daphne on queries.
Our client wants the errors on gRPC interface to have the right error code on `NotFound`.
> fix: replace query errors on the original modules into gRPC ones

- CHANGELOG.md
- x/collection/collection.go
- x/collection/collection_test.go
This patch would fix the default class ids of x/collection. It would be same as Daphne's.
- next ft class id: "00000000" -> "00000001"
- next nft class id: "10000000" -> "10000001"
> fix: fix default next class ids of x/collection

- CHANGELOG.md
- x/collection/keeper/supply.go
- x/collection/module/module.go
- x/foundation/module/module.go
- x/stakingplus/module/module.go
- x/token/module/module.go
This patch would fix possible non-determinism.
It also removes comments which has vulnerable logic.
> fix: do not loop enum in x/collection

- CHANGELOG.md
- client/grpc/tmservice/service_test.go
- x/foundation/keeper/internal/abci_test.go
- x/foundation/keeper/internal/treasury.go
- x/foundation/keeper/internal/treasury_test.go
This patch would check the generation of empty coins in x/foundation.
> chore: address generation of the empty coins in x/foundation

- CHANGELOG.md
- x/collection/keeper/grpc_query.go
- x/collection/keeper/grpc_query_test.go
This patch would make the following queries provide more specific error messages. The error code does not change.
- Query/TokenType
- Query/Token
Reported by @loin3.
> chore: provide specific error messages on x/collection queries

- CHANGELOG.md
- x/auth/tx2/service.go
- x/auth/tx2/service_test.go
I followd this [cosmos-sdk/issues/12040](https://github.com/cosmos/cosmos-sdk/issues/12040) and [cosmos-sdk/pull/12108](https://github.com/cosmos/cosmos-sdk/pull/12108)
our version 0.45.x does not have `GetBlockWithTxs` in `x/auth/tx/service`, so we create `x/auth/tx2`.
It's hard to cherr-pick because the directories are different. So I reflected the changes directly into tx2.
When query through `GetBlockWithTxs`, `invalid request` error occurred when no txs are included in block.
The correct behavior is to return the block with empty list of txs.
tested no error occured and return 0 length of tx list
before thsi PR, when tx does not exist in block
```
{
"code": 3,
"message": "out of range: cannot paginate 0 txs with offset 0 and limit 100: invalid request: invalid request",
"details": [] …
```
> fix: not to throw error when no txs in block

- .github/workflows/docker.yml
- CHANGELOG.md
Change the docker hub tag to new docker repository, `finschia/finschia-simapp`, with new authorization.
**⚠️ Warning**
**This docker hub authorization only can use current repository, cannot use in forked repository.**
Now we don't register `line/lbm-simapp`, so we need to change it.
>  ci: update docker action

- CHANGELOG.md
- RELEASE_CHANGELOG.md
- go.mod
- go.sum
* (baseapp) [\#840](https://github.com/Finschia/finschia-sdk/pull/840) allow querying the state based on `CheckState`.
* (x/foundation) [\#848](https://github.com/Finschia/finschia-sdk/pull/848) remove `gov mint` for x/foundation proposal
* (x/wasm) [\#850](https://github.com/Finschia/finschia-sdk/pull/850) remove `x/wasm` module in lbm-sdk
* (log) [\#883](https://github.com/Finschia/finschia-sdk/pull/883) add zerolog based rolling log system
* (Ostracon) [\#887](https://github.com/Finschia/finschia-sdk/pull/887) apply the changes of vrf location in Ostracon
* (x/upgrade) [\#889](https://github.com/Finschia/finschia-sdk/pull/889) remove time based upgrade
* (all) [\#970](https://github.com/Finschia/finschia-sdk/pull/970) change import path to `github.com/Finschia/finschia-sdk` and update …
> Release finschia-sdk v0.47.0

- CHANGELOG.md
- README.md
> docs: fix local swagger url

- CHANGELOG.md
- server/config/config.go
- server/config/config_test.go
- server/config/toml.go
- server/grpc/server.go
- server/start.go
- testutil/network/util.go
> feat: support custom r/w gRPC options

- CHANGELOG.md
- server/config/config.go
- server/config/config_test.go
- server/config/toml.go
- server/grpc/server.go
- server/start.go
- testutil/network/util.go
> feat: support custom r/w gRPC options (backport #1017)

- CHANGELOG.md
- x/collection/client/cli/tx.go
- x/collection/client/testutil/suite.go
- x/collection/client/testutil/tx.go
This patch would:
- add burn cli cmds to x/collection
- allow minting tokens of multiple classes
> feat: update x/collection cli for hackwasm2023

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (x/auth) [\#1011](https://github.com/Finschia/finschia-sdk/pull/1011) add the api for querying next account number
* (server/grpc) [\#1019](https://github.com/Finschia/finschia-sdk/pull/1019) support custom r/w gRPC options (backport #1017)
* (x/foundation) [\#999](https://github.com/Finschia/finschia-sdk/pull/999) migrate x/foundation FoundationTax into x/params
> Release finschia-sdk v0.47.1

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (server/grpc) [\#1018](https://github.com/Finschia/finschia-sdk/pull/1018) support custom r/w gRPC options (backport #1017)
* (x/auth) [\#1026](https://github.com/Finschia/finschia-sdk/pull/1026) add the api for querying next account number (backport #1011)
> Release finschia-sdk v0.47.2

- CHANGELOG.md
- go.mod
- go.sum
closes: #1039
* The latest version for `github.com/cosmos/ledger-cosmos-go` is `v0.13.0`. The latest version breaks some interfaces so I bump up with `v0.12.2`(the second latest one) which is enough to fix the issue.
* #1039 
* I tested with a nano S plus ledger on both Ubuntu 20.04 and Mac
> fix: unable to connect ledger nano S on Ubuntu

- baseapp/baseapp.go
WithMgsIndex just returns updated context not update context. This PR enables to update context.
> Fix increment of MsgIndex in context

- x/or/da/client/cli/query.go
- x/or/da/client/cli/tx.go
- x/or/da/module.go
closes: #XXXX
We will Implement `orda` CLI integration test after integrating `rollup` module with `orda` module in another PR. This PR focus on only CLI implementations.
> feat: add `orda/cc` CLI

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/testutil/messages.go
- x/auth/tx/service_test.go
- x/auth/vesting/msg_server.go
- x/auth/vesting/types/constants.go
- x/bank/keeper/msg_server.go
- x/bank/types/events.go
- x/crisis/keeper/msg_server.go
- x/crisis/types/events.go
- x/distribution/keeper/msg_server.go
- x/distribution/types/events.go
- x/evidence/keeper/msg_server.go
- x/evidence/types/events.go
- x/feegrant/events.go
- x/gov/keeper/msg_server.go
- x/gov/types/events.go
- x/slashing/keeper/msg_server.go
- x/slashing/types/events.go
- x/staking/keeper/msg_server.go
- x/staking/types/events.go
This patch would add message event to every msgs in a tx. The event contains following attributes:
- sender
- action
- module
You may refer to the corresponding PR of the upstream.
> refactor: automate EventTypeMessage inclusion in every message execution (backport cosmos/cosmos-sdk#13532)

- CHANGELOG.md
- baseapp/baseapp.go
- types/events.go
- types/events_test.go
> fix: improve baseapp event emission (backport cosmos/cosmos-sdk#14356)

- CHANGELOG.md
- client/grpc/tmservice/service_test.go
- x/foundation/keeper/internal/treasury.go
> fix: address generation of the empty coins in x/foundation (backport #952)

- CHANGELOG.md
- docs/docs/core/08-events.md
This patch would add documentation about default events by baseapp.
refer: #1063
> docs: document default events

- CHANGELOG.md
- baseapp/baseapp.go
- baseapp/testutil/messages.go
- x/auth/tx/service_test.go
- x/auth/vesting/msg_server.go
- x/auth/vesting/types/constants.go
- x/bank/keeper/msg_server.go
- x/bank/types/events.go
- x/crisis/keeper/msg_server.go
- x/crisis/types/events.go
- x/distribution/keeper/msg_server.go
- x/distribution/types/events.go
- x/evidence/keeper/msg_server.go
- x/evidence/types/events.go
- x/feegrant/events.go
- x/gov/keeper/msg_server.go
- x/gov/types/events.go
- x/slashing/keeper/msg_server.go
- x/slashing/types/events.go
- x/staking/keeper/msg_server.go
- x/staking/types/events.go
This patch backports #1063 into v0.48.0 release candidate.
> refactor: automate EventTypeMessage inclusion in every message execution (backport #1063)

- CHANGELOG.md
- server/start.go
- server/start_test.go
* Fix for redundant key generation. With running kms, generating priv-key is unnecessary.
> fix: fix redundant priv-validator-key generation when running with kms

- .github/workflows/test.yml
- .gitmodules
- CHANGELOG.md
- Makefile
Remove unused shared library
- libsodium
Same as this pr. https://github.com/Finschia/finschia/pull/240
> feat!: remove libsodium vrf library.

- CHANGELOG.md
- x/collection/msgs.go
- x/collection/msgs_test.go
> fix: reject modifying NFT class with token index filled in MsgModify

- CHANGELOG.md
- x/collection/keeper/migrations/v2/store.go
This patch would support old chains in which the default class ids start from 0.
related: #1105
> fix: support x/collection migration on old chains

- CHANGELOG.md
This patch would introduce "Event Breaking" section in CHANGELOG.md.
Our client considers the changes in the events as Client Breaking. Hence, we added another section, "Event Breaking" and will keep tracking on it.
> chore: introduce Event Breaking section in CHANGELOG

- CHANGELOG.md
- x/collection/keeper/supply_test.go
This patch would compare the statistics before and after the supply operations.
related: #1105
> refactor: check statistics and balance on x/collection mint and burn operations

- CHANGELOG.md
This patch would introduce following sections into CHANGELOG.md.
- Event Breaking Change
- State Machine Breaking
Our client considers the changes in the events as Client Breaking. Hence, we added another section, "Event Breaking" and will keep tracking on it.
> chore: introduce detailed breaking sections in CHANGELOG

- CHANGELOG.md
- x/foundation/README.md
This patch would update links in x/foundation README.md
> docs: update links in x/foundation README.md

- CHANGELOG.md
- x/foundation/client/cli/tx.go
- x/foundation/client/testutil/tx.go
This patch would add update-censorship command, which helps generating Msg/UpdateCensorship.
> feat: add update-censorship cmd to x/foundation cli

- CHANGELOG.md
- docs/docs/core/08-events.md
It seems better to add more detailed information about default events emitted by baseapp. (Especially information about the event structure.)
This PR is trying to add such information to the document created by #1081.
> docs: add detailed explanation about default events

- CHANGELOG.md
- x/token/errors.go
- x/token/keeper/keeper_test.go
- x/token/keeper/msg_server_test.go
- x/token/msgs_test.go
* Add testcases for mint, burn, modify
> test(token): add additional testcase(mint, burn, modify)

- CHANGELOG.md
- x/collection/keeper/msg_server_test.go
* This PR refactors tests for `SendFT`, `OperatorSendFT`, `AuthorizeOperator`, and `RevokeOperator` to check more states
> test(collection): add more verify logics for tests(SendFT, OperatorSendFT, Authorize, Revoke)

- CHANGELOG.md
- x/token/keeper/msg_server_test.go
* add test for event compatibility with literal event structure that was used previously
* These tests act as regression tests for event structure
> test: add test for event compatibility

- CHANGELOG.md
- testutil/encoding.go
- testutil/encoding_test.go
- x/collection/keeper/keeper_test.go
- x/collection/keeper/msg_server_test.go
closes: #XXXX
* remove deterministic flag. Only test with random addresses, but events can be generated by those value
* remove all helper functions for generating a event
* add some global test helper functions to reduce repetition
* add more test for `MsgOperatorBurnFT`
> test(collection): refactor overall unittests of `x/collection`

- CHANGELOG.md
- testutil/encoding.go
- testutil/encoding_test.go
- x/token/keeper/keeper_test.go
- x/token/keeper/msg_server_test.go
* Just refactoring testcases for token module
> test(token): refactoring testcase for token

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (x/auth) #1011
* (server/grpc) #1017 
* (x/auth) #1085
* (proto) #1087
* (third_party/proto) #1037
* (ostracon) #1057
* (x/foundation) #1072
* (cli) #1086
* (ostracon) #1089
* (ostracon) #1099
* (refactor) #1114
* (x/token) #1128
* (x/token) #1129
* (x/token) #1130
* (x/collection) #1131
* (x/collection) #1133
* (x/token) #1137
* (x/collection) #1139
* (x/token) #1140
* (ostracon) #1142
* (ledger) #1040
* (x/foundation) #1053
* (baseapp) #1091
* (x/foundation) #1108
* (x/foundation) #999
* (x/collection) #1102
* (x/collection) #1105
* (x/collection) #1106
* (refactor) #1090
* (x/bank) #1093
* (baseapp) #1092
* (x/foundation) #1053
* (build,ci) #1043
* (readme) #997
* (docs) #1094
> Release finschia-sdk v0.48.0

- .github/workflows/tag.yml
- CHANGELOG.md
- Makefile
closes: #1146 
Replace gorelease image to official image. And also change base golang version to v1.20.
> fix: github release ci error

- CHANGELOG.md
- crypto/hd/hdpath.go
- crypto/keys/secp256k1/secp256k1.go
- crypto/keys/secp256k1/secp256k1_internal_test.go
- crypto/keys/secp256k1/secp256k1_nocgo.go
- crypto/keys/secp256k1/secp256k1_nocgo_test.go
- crypto/keys/secp256k1/secp256k1_test.go
- crypto/ledger/ledger_mock.go
- crypto/ledger/ledger_notavail.go
- crypto/ledger/ledger_secp256k1.go
- go.mod
- go.sum
- server/rosetta/converter.go
closes: #XXXX
* Replace btcsuite [secp, ecdsa] with latest decreds library (updating some secp256k1 logics)
ref. https://github.com/cosmos/cosmos-sdk/pull/13513, https://github.com/cosmos/cosmos-sdk/pull/14123, https://github.com/cosmos/cosmos-sdk/pull/15018
> chore(deps, crypto): use secp directly instead of wrapper

- CHANGELOG.md
- x/crisis/keeper/keeper.go
- x/foundation/keeper/internal/invariants.go
closes: #865 
ref. https://github.com/cosmos/cosmos-sdk/pull/14588
> feat: use CacheContext() in AssertInvariants()

- CHANGELOG.md
- x/auth/tx/service.go
- x/slashing/handler_test.go
- x/slashing/keeper/hooks.go
- x/slashing/keeper/infractions.go
- x/slashing/keeper/keeper_test.go
- x/slashing/spec/04_begin_block.md
- x/slashing/spec/05_hooks.md
Modify missing changes of converting to tendermint
* revert Ostracon slashing changes (revert #347)
* revert block converting
related: #1177
> chore: modify missing changes of converting to tendermint

- .github/workflows/test.yml
- .golangci.yml
- CHANGELOG.md
- scripts/go-lint-all.bash
- tests/e2e/foundation/grpc.go
- tests/e2e/foundation/query.go
- tests/e2e/foundation/suite.go
- tests/e2e/foundation/tx.go
- tests/go.mod
- tests/go.sum
- x/foundation/authz.go
- x/foundation/events.go
- x/foundation/foundation.go
- x/foundation/genesis.go
- x/foundation/go.mod
- x/foundation/keeper/internal/grpc_query.go
- x/foundation/msgs.go
The e2e test for x/foundation did not check the error code of the txs result.
Applying this patch, the test would check the tx result included in the blocks.
minor: update gogoproto package
> test: check tx result on x/foundation e2e test

- x/zkauth/types/msgs.go
The cachedValue of types.Any is accessed using m.GetCachedValue() of MsgExecution, but the value does not exist.
GetCachedValue: https://github.com/Finschia/finschia-sdk/commit/ca6ca76ea1eb5d3aff74bb8fe8910445c3b456ed#diff-39e18d04623a49896a23eaa0d8f555e86d380907384bb93160bcbf7ac8c89e02R66
I implement UnpackInterfaces like txBody.
txBody.UnpackInterfaces: https://github.com/Finschia/finschia-sdk/blob/ca6ca76ea1eb5d3aff74bb8fe8910445c3b456ed/types/tx/types.go#L170-L180
A value is added to cachedValue by implementing UnpackInterfaces.
https://github.com/Finschia/finschia-sdk/blob/ca6ca76ea1eb5d3aff74bb8fe8910445c3b456ed/codec/types/interface_registry.go#L249
> Add UnpackInterfaces to MsgExecute 

- CHANGELOG.md
- baseapp/block_gas_test.go
- simapp/ante/ante.go
- x/zkauth/ante/zkauth.go
- x/zkauth/ante/zkauth_test.go
- x/zkauth/testutil/keeper.go
zkauth uses a ephemeral key to perform tx signature and includes zkauth signature in msg.
- Ephemeral keys do not have the ability to pay fees, so ignore DeductFeeDecorator when zkauth is included.
- It is originally necessary to subtract the fee from the zkauth address, but I will leave this as a todo and temporarily decide that the fee will not occur.
> Ignore gas when zkauth

- CHANGELOG.md
- x/auth/types/account.go
- x/auth/types/account_test.go
closes: #XXXX
ref. https://github.com/cosmos/cosmos-sdk/pull/16554
> fix(x/auth): ensure nil .BaseAccounts are reported in ModuleAccount.Validate

- CHANGELOG.md
- baseapp/block_gas_test.go
- x/foundation/keeper/internal/genesis.go
- x/foundation/keeper/internal/genesis_test.go
* (audit issue) add init logic of foundation module accounts to InitGenesis in order to eliminate potential panic
* ~NOTE: This is likely to change account number state in auth module.~ --> InitGenesis never runs more than once
> fix: add init logic of module accounts just in case

- CHANGELOG.md
- x/collection/msgs.go
- x/collection/msgs_test.go
closes: #XXXX
This PR adds nft id validation to MsgSendNFT.
The ValidateBasic() method of message MsgSendNFT is used to check the validity of the message during the stateless validation process. The current implementation of ValidateBasic() checks whether the provided IDs are valid TokenIDs with function ValidateTokenID():
It is insufficient as it allows Fungible tokens to pass through, potentially leading to unexpected errors since Fungible tokens are not intended to be processed by this function.
> fix: add nft id validation to MsgSendNFT

- CHANGELOG.md
- x/collection/msgs.go
- x/collection/msgs_test.go
- x/token/msgs.go
- x/token/msgs_test.go
This PR uses accAddress instead of address to compare in the `validatebasic` function in the collection & token modules.
Before this PR, it used case-sensitive comparison, thus it would occur a bug when `holder` and `operator` are the same but in different capitalization.
> fix: use accAddress to compare in validatebasic function in collection & token modules

- CHANGELOG.md
- x/collection/keeper/genesis.go
- x/collection/keeper/genesis_test.go
x/collection does not export its params into genesis. This patch addresses the problem.
> fix: export x/collection params into genesis

- CHANGELOG.md
- x/collection/msgs.go
- x/collection/msgs_test.go
This patch renames `validateCoins()` into `validateFTCoins()` and update its logic to reject valid _NFT_ coins.
`validateCoins()` are only used on FT APIs, but does not reject NFT coins. This patch addresses the problem.
> fix: reject NFT coins on FT APIs

- CHANGELOG.md
- x/foundation/module/module.go
- add missing error handling for x/foundation migration.
- error handling is from #1171
> fix: add error handling for x/foundation migration

- CHANGELOG.md
- x/zkauth/keeper/keeper.go
- x/zkauth/keeper/keeper_test.go
- x/zkauth/keeper/msg_server.go
- x/zkauth/keeper/msg_server_test.go
Currently, msgs signer validation is not performed when dispatching msgs of MsgExcute.
This leads to serious problems such as fraudulent transfers.
This can be prevented by making sure that the signer of the msg executed when dispatching msg is the signer of MsgExcute.
We will have to discuss later whether this modification is sufficient.
> Compare the signer of the normal message and the signer of MsgExcute

- CHANGELOG.md
- Makefile
Extract the version of Finschia/ostracon from `go.mod` and set the flag on the build.
Finschia/ostracon does not set its version even in the release branches, while the upstream tendermint sets its version.
Hence, we won't apply this patch on the main, which uses tendermint already.
1. `make build`
2. `./build/simd ostracon version`
> build: set Finschia/ostracon version

- CHANGELOG.md
- client/tx/factory.go
* (audit issue) fix possible overflow in BuildUnsignedTx
* referenced implementation(https://github.com/cosmos/cosmos-sdk/pull/18622)
> fix: possible overflow in BuildUnsignedTx

- CHANGELOG.md
- x/staking/keeper/validator.go
Cherry-pick of:
- cosmos/cosmos-sdk#12303
> fix: Use bytes instead of string comparison in delete validator queue (backport cosmos/cosmos-sdk#12303)

- CHANGELOG.md
- x/gov/keeper/grpc_query.go
- x/gov/keeper/grpc_query_test.go
The TallyResult() is used to fetch the tally result from a proposal, in which the case when a proposal fails does not provide the correct information as this case has been branched into the default case.
This pr cherry-pick the following pr:
- https://github.com/cosmos/cosmos-sdk/pull/19725
> fix: fetch a failed proposal tally from proposal.FinalTallyResult in the gprc query

- CHANGELOG.md
- simapp/app.go
- x/slashing/keeper/slash_redelegation_test.go
- x/staking/keeper/slash.go
closes: #XXXX
According to the [GHSA-86h5-xcpx-cfqc](https://github.com/advisories/GHSA-86h5-xcpx-cfqc), an issue was identified in the slashing mechanism that may allow for the evasion of slashing penalties during a slashing event. If a delegation contributed to the byzantine behavior of a validator and the validator has not yet been slashed, it may be possible for that delegation to evade a pending slashing penalty through re-delegation behavior. 
Additional validation logic was added to restrict this behavior in below commit in cosmos-sdk.
https://github.com/cosmos/cosmos-sdk/commit/d1b5b0c5ae2c51206cc1849e09e4d59986742cc3
> fix: add validation for potential slashing evasion during re-delegation

- CHANGELOG.md
- client/keys/delete.go
- client/keys/delete_test.go
If you provide a list of keys to the keys delete command, it will stop and fail if one of those keys is not found.
This pr cherry-pick the following pr:
- https://github.com/cosmos/cosmos-sdk/pull/18562
> fix: ignore error when key not found in keys delete

- CHANGELOG.md
- simapp/test_helpers.go
- types/coin.go
- types/coin_test.go
- types/dec_coin.go
- types/dec_coin_test.go
- x/auth/legacy/v043/store_test.go
- x/auth/vesting/types/vesting_account.go
- x/auth/vesting/types/vesting_account_test.go
- x/bank/keeper/genesis.go
- x/bank/keeper/grpc_query_test.go
- x/bank/keeper/invariants.go
- x/bank/keeper/querier_test.go
- x/bank/types/genesis.go
- x/bank/types/msgs.go
- x/distribution/keeper/delegation.go
- x/distribution/keeper/genesis.go
- x/distribution/keeper/invariants.go
- x/foundation/keeper/internal/invariants.go
- x/gov/abci_test.go
- x/gov/genesis.go
- x/gov/keeper/deposit_test.go
- x/gov/keeper/invariants.go
- x/gov/types/params.go
- x/mint/types/minter_test.go
- x/staking/genesis.go
- x/staking/types/msg_test.go
closes: #XXXX
cherry-pick: https://github.com/cosmos/cosmos-sdk/pull/14739
> fix: replace IsEqual with Equal

- CHANGELOG.md
- store/rootmulti/store.go
- store/rootmulti/store_test.go
* (audit issue) app-hash mismatch if upgrade migration commit is interrupted
* backport: cosmos/cosmos-sdk#13530
> fix: app-hash mismatch if upgrade migration commit is interrupted(backport cosmos/cosmos-sdk#13530)

- CHANGELOG.md
- x/auth/client/cli/tx_multisign.go
- x/auth/client/cli/tx_sign.go
- x/auth/client/testutil/suite.go
closes: #XXXX
When signing an multisig tx, you are required to provide the multisig address (--multisig) and the key you are signing with (--from), but there's no check that the key is actually part of the multisig. This makes it very easy to accidentally sign with the wrong key and only figure it out when you try to broadcast the invalid tx that includes a signature from a key thats not in the multisig.
- backport cosmos/cosmos-sdk#12548
> fix: prevent signing from wrong key in multisig

- CHANGELOG.md
- x/mint/types/params.go
- x/slashing/types/params.go
* fix: update param validation to fail on nil dec
* refer: https://github.com/cosmos/cosmos-sdk/pull/13553
> fix: update param validation to fail on nil dec

- CHANGELOG.md
- server/config/config.go
- server/config/config_test.go
- server/config/toml.go
* fix for multiple gas parsing
* cosmos/cosmos-sdk#18537
> fix(server): properly parse multiple gas config(backport cosmos/cosmos-sdk#18537)

- CHANGELOG.md
- x/fbridge/keeper/keeper.go
- x/fbridge/keeper/keeper_test.go
> fix: fbridge auth checking bug

- CHANGELOG.md
- x/fswap/keeper/grpc_query.go
- x/fswap/keeper/keys.go
- x/fswap/keeper/keys_test.go
- x/fswap/types/fswap.go
- x/fswap/types/msgs.go
* fix: update swap keys for possibly overlapped keys
* They should be the same -> `(hello, world)` != `(hell, oworld)`
> fix: update swap keys for possibly overlapped keys

- CHANGELOG.md
- client/docs/swagger-ui/swagger.yaml
- x/fbridge/module/module.go
- x/fbridge/types/codec.go
- x/fbridge/types/keys.go
- x/fbridge/types/msgs.go
- x/fbridge/types/msgs_test.go
- x/fswap/types/keys.go
- x/fswap/types/msgs.go
- x/fswap/types/msgs_test.go
* Fix bug where amino is not supported in fswap and fbridge
> Fix bug where amino is not supported in fswap and fbridge

- CHANGELOG.md
- crypto/keys/multisig/codec.go
- x/fswap/keeper/keeper.go
- x/fswap/module.go
* Add missing router registration
> fix: add missing router registration

- CHANGELOG.md
- Makefile
* ~refresh docker container's bound volume which refer to current working directory~
* use current directory as a suffix for docker container to run it per their environment
* ~Without refreshing docker container with bound volume location,~ It doesn't generate `proto`, `swagger` depending on the current working directory
* For example
* Does work for `~/Finschia/fisnchia-sdk`
* Doesn't work for `~/xxx/finschia-sdk`
* to work this, you should remove docker container first.
> build: add suffix string to docker container

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (x/fswap) #1336
* (x/fswap) #1339
* (x/fbridge) #1340
* (x/fbridge) #1347
* (x/fbridge) #1351
* (x/fswap) #1345
* (x/fbridge) #1360
* (types) #1317
* (x/fswap) #1364
* (x/fbridge) #1368
* (x/fbridge) #1370
* (x/fswap) #1373
* (x/fswap) #1389
* (x/fswap) #1390
* (x/fbridge) #1400
* (x/fswap) #1397
* (x/fswap) #1399
* (x/auth) #1281
* (x/foundation) #1283
* (x/collection) #1282
* (x/collection) #1290
* (x/foundation) #1295
* (sec) #1305
* (client) #1307
* (types) #1308
* (x/staking) #1309
* (client/keys) #1315
* (store) #1318
* (types) #1320
* (x/crypto) #1322
* (x/auth) #1324
* (x/mint, x/slashing) #1325
* (x/server) #1343
* (x/fbridge) #1362
* (x/fswap) #1367
* (x/fswap) #1381
* (x/fswap, x/fbridge) #1380
* (x/fswap) #1386
* (x/fswap) #1398
* (build) #1298
* (x/token,collection) #1202
* …
> Release finschia-sdk v0.49.0
