Finschia/finschia-sdk

- client/tx/tx.go
For now following command fails.
```
simd start
simd keys add test --keyring-backend test
simd tx auth empty [new_address] --keyring-backend test --chain-id sim
Error: {"codespace":"sdk","code":22,"message":"rpc error: code = NotFound desc = account [new_address] not found: key not found"}
```
I tested this at previous PR(https://github.com/line/lfb-sdk/pull/265) but I think I tested something wrong then.
This is a problem caused by mischecking the type of on error in the query response.
The type of error that is returned by `accountRetriever.GetAccountSequence` is not `sdkerror.Error` but `client.Error`.
I fixed it.
closes: #XXXX
---
checked off. If any of the checklist items are not applicable, please …
> fix: send tx with unknown address with daemon command

- client/docs/swagger-ui/swagger.yaml
- scripts/protoc-swagger-gen.sh
closes: #249 
wasmd 0.17.0(#249) After merging, the legacy style wasm proto path was fixed.  This PR purpose is follow-up.
However, wasm doesn't have a service.proto, so it doesn't change swagger for wasm.
Other than that, it contains what appears to be missing during the merging of main in PR #249.(e.g reverted COSMOS SDK->LFB SDK)
---
> docs: update swagger proto path for wasm

- README.md
- Add: Quick Start Guide docs
closes: #XXXX
---
> docs: update quick start guide

- .github/workflows/release-sims.yml
- Makefile
- RELEASE_CHANGELOG.md
> docs: update release changelog

- CHANGELOG.md
- x/slashing/client/cli/query.go
No args for this command.
Related PR of cosmos: https://github.com/cosmos/cosmos-sdk/pull/8427
---
> fix: fix query signing infos command

- .github/workflows/test.yml
> ci: fix branch name on ci script

- go.mod
- go.sum
- x/wasm/keeper/api.go
- x/wasm/keeper/wasmtesting/mock_engine.go
- x/wasm/types/wasmer_engine.go
Closes https://github.com/line/cosmwasm/issues/144, https://github.com/line/cosmwasm/pull/153, https://github.com/line/wasmvm/pull/55
It's a poc implementation.
Gas consumption, security checks, unit tests, CI, etc. need to be checked.
These checks will be registered as separate PRs targeting `dynamic_link` branch.
---
> feat: impl GetContractEnv of cosmwasmAPI

- go.mod
- go.sum
- x/wasm/keeper/api.go
closes: https://github.com/line/cosmwasm/pull/182 https://github.com/line/wasmvm/pull/61
Pass the contract env through the existing cgo API.
> feat: add returning the contract env for GlobalAPI

- .github/dependabot.yml
Remove reviewers on dependabot.yml
> Remove reviewers on dependabot.yml

- .github/workflows/bench.yml
- CHANGELOG.md
This PR adds a benchmark for CosmWasmAPI to github actions.
Sample execution: https://github.com/line/lbm-sdk/runs/8150140720?check_suite_focus=true
> ci: add benchmarking job to ci

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* feat: enable querying based on mempool status (only gRPC) 
* refactor: Remove useless stub BeginBlock/EndBlock methods
* feat: Remove x/wasm module
* feat: detach ibc module
* fix: foundation amino codec
* feat!: apply changes to replace Ostracon proto message with Tendermint
* feat: add zerolog based rolling log system
* feat: remove time-based upgrade
* Map Ostracon:ErrTxInMap to lbm-sdk:ErrTxInMempoolCache
The detail changes can be seen in [CHANGELOGS](https://github.com/line/lbm-sdk/blob/66a424cc2c9a04c699901d43fa4f4f5f963a1317/RELEASE_CHANGELOG.md)
> chore: release v0.47.0-alpha1

- CHANGELOG.md
- x/foundation/README.md
> docs: update permlinks in x/foundation documents

- CHANGELOG.md
- baseapp/baseapp.go
- types/events.go
- types/events_test.go
This patch backports #1075 into v0.48.0 release candidate.
> fix: improve baseapp event emission (backport #1075)

- CHANGELOG.md
- docs/docs/core/08-events.md
This patch backports #1081 into v0.48.0 release candidate.
> docs: document default events (backport #1081)

- baseapp/abci.go
- go.mod
- go.sum
closes: #XXXX
Since abci of ostracon for ramus has been updated, apply the fix to finschia-sdk for L1.
> Update ostracon to b9cf421a361e

- CHANGELOG.md
- RELEASE_CHANGELOG.md
* (x/foundation) #1061
* (baseapp) #1075
* (baseapp) #1079
* (refactor) #1063
* (x/bank) #1066
* (docs) #1081
> Release finschia-sdk v0.47.3

- .github/workflows/docker.yml
- CHANGELOG.md
This PR fixes some comments in workflow.
This workflow does not triggered tags without patch number.
> chore: fix tag comments in github actions workflow docker.yml

- demo/README.md
- demo/reset.sh
- demo/run_chain.sh
- demo/run_sequencer.sh
- demo/test_sequencer.sh
> docs: Update script

- demo_init_node.sh
Add the script required when demoing zkauth using finschia node.
I am modifying the config file to configure settings to enable insecure cors and the rest of the server.
This script is intended for demo purposes, so please do not use it in production.
> Add init script for demo

- .mergify.yml
- CHANGELOG.md
* add v0.49.x for backport mergify
> ci: add v0.49.x for backport mergify
